'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aluno
    Public Property id_aluno As Integer
    Public Property email As String
    Public Property login As String
    Public Property senha As String
    Public Property nome_aluno As String
    Public Property telefone As String
    Public Property data_nasc As Date
    Public Property CPF As String

    Public Overridable Property Matricula As ICollection(Of Matricula) = New HashSet(Of Matricula)

End Class
