//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.Aluno_Materia = new HashSet<Aluno_Materia>();
            this.Aluno_Professor_Materia = new HashSet<Aluno_Professor_Materia>();
        }
    
        public int id_aluno { get; set; }
        public int id_pessoa { get; set; }
        public string situacao { get; set; }
        public string observacao { get; set; }
        public Nullable<double> rendimento { get; set; }
        public string matricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aluno_Materia> Aluno_Materia { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aluno_Professor_Materia> Aluno_Professor_Materia { get; set; }
    }
}
