//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno_Materia
    {
        public int id_aluno_materia { get; set; }
        public int id_aluno { get; set; }
        public int id_materia { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
