//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno_Professor_Materia
    {
        public int id_aluno_prof_mat { get; set; }
        public int id_aluno { get; set; }
        public int id_professor_materia { get; set; }
        public double nota { get; set; }
        public System.DateTime data_matricula { get; set; }
        public double frequencia { get; set; }
        public Nullable<bool> atestado { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual Professor_Materia Professor_Materia { get; set; }
    }
}
