'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Curso
    Public Property id_curso As Integer
    Public Property nome_curso As String
    Public Property duracao As String
    Public Property turno As String

    Public Overridable Property Disciplina As ICollection(Of Disciplina) = New HashSet(Of Disciplina)

End Class
