'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Disciplina
    Public Property id_disciplina As Integer
    Public Property nome_disciplina As String
    Public Property inicio As String
    Public Property fim As String
    Public Property id_curso As Integer

    Public Overridable Property Curso As Curso
    Public Overridable Property Professor As ICollection(Of Professor) = New HashSet(Of Professor)

End Class
