'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class MatriculadbEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=MatriculadbEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Admin() As DbSet(Of Admin)
    Public Overridable Property Aluno() As DbSet(Of Aluno)
    Public Overridable Property Curso() As DbSet(Of Curso)
    Public Overridable Property Disciplina() As DbSet(Of Disciplina)
    Public Overridable Property Matricula() As DbSet(Of Matricula)
    Public Overridable Property Professor() As DbSet(Of Professor)

End Class
