'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Matricula
    Public Property id_matricula As Integer
    Public Property data_matricula As Date
    Public Property id_aluno As Integer
    Public Property id_professor As Integer

    Public Overridable Property Aluno As Aluno
    Public Overridable Property Professor As Professor

End Class
