'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Professor
    Public Property id_professor As Integer
    Public Property nome_professor As String
    Public Property CPF As String
    Public Property telefone As String
    Public Property id_disciplina As Integer

    Public Overridable Property Disciplina As Disciplina
    Public Overridable Property Matricula As ICollection(Of Matricula) = New HashSet(Of Matricula)

End Class
