//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitacao
    {
        public int id_solicitacao { get; set; }
        public int id_funcionario { get; set; }
        public string tipo_documento { get; set; }
        public System.DateTime data_pedido { get; set; }
        public System.DateTime data_emissao { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
