//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matricula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public int id_pessoa { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public string permissoes { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
